CREATE TABLE association
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255) NOT NULL UNIQUE,
    website  VARCHAR(2048),
    location VARCHAR(255)
);

CREATE TABLE competitor
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name     VARCHAR(255) NOT NULL,
    last_name      VARCHAR(255),
    association_id INTEGER,

    CONSTRAINT fk_competitor_association
        FOREIGN KEY (association_id)
            REFERENCES association (id)
);

CREATE TABLE tournament
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    date      DATE         NOT NULL,
    image_url VARCHAR(2048)
);

CREATE TABLE category_type
(
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_name         VARCHAR(255) NOT NULL UNIQUE,
    description        VARCHAR(255) NOT NULL,
    scores_per_attempt INTEGER NOT NULL
        CHECK (scores_per_attempt > 0)
);

CREATE TABLE category
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255) NOT NULL,
    initial_fee      DECIMAL(6, 2) NOT NULL
        CHECK (initial_fee BETWEEN 0 AND 10000),
    additional_fee   DECIMAL(6, 2) NOT NULL
        CHECK (additional_fee BETWEEN 0 AND 10000),
    attempt_limit    INTEGER NOT NULL
        CHECK (attempt_limit > 0),
    tournament_id    INTEGER NOT NULL,
    category_type_id INTEGER NOT NULL,
    image_url        VARCHAR(2048),

    CONSTRAINT fk_category_tournament
        FOREIGN KEY (tournament_id)
            REFERENCES tournament (id),

    CONSTRAINT fk_category_type
        FOREIGN KEY (category_type_id)
            REFERENCES category_type (id)
);

CREATE TABLE attempt
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competitor_id INTEGER NOT NULL,
    category_id   INTEGER NOT NULL,

    CONSTRAINT fk_attempt_competitor
        FOREIGN KEY (competitor_id)
            REFERENCES competitor (id),

    CONSTRAINT fk_attempt_category
        FOREIGN KEY (category_id)
            REFERENCES category (id)
);

CREATE TABLE score
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    score      DECIMAL(4, 2) NOT NULL
        CHECK (score BETWEEN 0 AND 10),
    attempt_id INTEGER NOT NULL,
    x          SMALLINT,
    y          SMALLINT,

    CONSTRAINT fk_score_attempt
        FOREIGN KEY (attempt_id)
            REFERENCES attempt (id),

    CONSTRAINT score_x_range
        CHECK (x IS NULL OR x BETWEEN 0 AND 200),

    CONSTRAINT score_y_range
        CHECK (y IS NULL OR y BETWEEN 0 AND 200),

    CONSTRAINT score_coordinates_together
        CHECK (
            (x IS NULL AND y IS NULL)
                OR
            (x IS NOT NULL AND y IS NOT NULL)
            )
);