CREATE TABLE app_user
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(50) NOT NULL,
    CONSTRAINT app_user_role_check
        CHECK (role IN ('SUPER_ADMIN', 'ADMIN'))
);